version: '2'
services:
    jhiptruffle-app:
        image: jhiptruffle
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://jhiptruffle-mariadb:3306/jhiptruffle
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhiptruffle-mariadb:
        extends:
            file: mariadb.yml
            service: jhiptruffle-mariadb
